spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
#  security:
#    oauth2:
#      resourceserver:
#        opaque-token:
#          introspection-uri: https://idp.example.com/introspect
#          client-id: client
#          client-secret: secret

server:
  port: 8080

logging:
  level:
    org.springframework.security: trace