CREATE TABLE CATEGORY (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORY (name) VALUES ('Leisure');
INSERT INTO CATEGORY (name) VALUES ('Food');
INSERT INTO CATEGORY (name) VALUES ('Market');
INSERT INTO CATEGORY (name) VALUES ('Pharmacy');
INSERT INTO CATEGORY (name) VALUES ('Others');
